"""nuevos campos en el modelo usuario

Revision ID: 240d60c28fe7
Revises: 498d4dd5641c
Create Date: 2023-12-27 19:54:31.942442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240d60c28fe7'
down_revision = '498d4dd5641c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acerca_mi', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('ultima_conexion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('ultima_conexion')
        batch_op.drop_column('acerca_mi')

    # ### end Alembic commands ###
