"""flask db migrate

Revision ID: 24a21464975f
Revises: ccb91d7ea51a
Create Date: 2024-01-01 22:44:31.961468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a21464975f'
down_revision = 'ccb91d7ea51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.drop_table('seguidores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('seguidor_id', sa.INTEGER(), nullable=False),
    sa.Column('seguidores_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['seguidores_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('seguidor_id', 'seguidores_id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
