"""posts table

Revision ID: 498d4dd5641c
Revises: 6334bb499924
Create Date: 2023-12-24 13:36:30.245568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498d4dd5641c'
down_revision = '6334bb499924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=140), nullable=False),
    sa.Column('tiempo_publicado', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_tiempo_publicado'), ['tiempo_publicado'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_post_tiempo_publicado'))

    op.drop_table('post')
    # ### end Alembic commands ###
