"""private messages

Revision ID: 96a983e1c6d4
Revises: 6dc1b3956870
Create Date: 2024-01-29 20:34:08.230227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a983e1c6d4'
down_revision = '6dc1b3956870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=170),
               existing_nullable=False)
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=170),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('contrasena_hash',
               existing_type=sa.String(length=170),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.String(length=170),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
