"""Message changes name row

Revision ID: a3d8750c277e
Revises: 2adb63d4282a
Create Date: 2024-01-31 23:43:44.551611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d8750c277e'
down_revision = '2adb63d4282a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_publicado', sa.DateTime(), nullable=False))
        batch_op.drop_index('ix_message_timestamp')
        batch_op.create_index(batch_op.f('ix_message_tiempo_publicado'), ['tiempo_publicado'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_message_tiempo_publicado'))
        batch_op.create_index('ix_message_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('tiempo_publicado')

    # ### end Alembic commands ###
