"""creacion de la tabla seguidores

Revision ID: ccb91d7ea51a
Revises: 240d60c28fe7
Create Date: 2023-12-30 15:51:04.630022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb91d7ea51a'
down_revision = '240d60c28fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.Column('seguidores_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['seguidores_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('seguidor_id', 'seguidores_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidores')
    # ### end Alembic commands ###
